spring:
  application:
    name: todo-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

    #security:
    #user:
    #name: admin
    #password: admin
    #roles: user

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false  # To improve performance
    #show-sql: true

server:
  port: ${RUNNING_PORT}