spring:
  application:
    name: todo-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false  # To improve performance
    #show-sql: true

server:
  port: ${RUNNING_PORT}