spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false  # To improve performance
    #show-sql: true

jwt:
  secret: ${MY_SECRET_KEY}  # JWT secret key

server:
  port: ${RUNNING_PORT}